#!/bin/bash
#Purpose: Monitoring Disk Space Utilisation and Send Email Alert 
#Version:1.0
#Created Date: Thu May 24 
#Author: Arun Kumar Rout
# START #
THRESHOLD=80
mailto="abcd@example.com"
HOSTNAME=$ (hostname)    #for knowing which hostanem is critical, so passed the variable

for path in '/bin/df -h | grep -vE 'Filesystem| tmpfs' | awk '{print $5}' | sed 's/%//g' '
do 
      if [ $path -ge $THRESHOLD ]; then
      df -h | grep $path% >> /tmp/temp
      fi
done

VALUE= ' cat /tmp/temp | wc -1 '
                  if [ $VALUE -ge 1 ] ; then
                  mail -s  "$HOSTNAME CPU of VM goes  above 80%" $mailto < /tmp/temp
                  fi
rm -rf  /tmp/temp  
